language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "10"
script:
  - npm install
  - npm run build
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success: 'npm run coveralls'